spring:
  application: { name: gateway }
  cloud:
    nacos: { discovery: { server-addr: "${NACOS_ADDR:localhost:8848}" } }
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
        - id: points
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/points/**
        - id: incentive
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/activities/**,/api/v1/exchanges/**,/api/v1/lotteries/**
        - id: award
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/awards/**
server: { port: 8080 }
management: { endpoints: { web: { exposure: { include: health,info,metrics } } } }
