spring:
  config:
    activate:
      on-profile: local

xxl:
  job:
    admin:
      addresses: http://localhost:8088
    executor:
      enabled: true
      appname: incentive-lottery-service
      address: http://host.docker.internal:9998
      port: 9998
      log-path: ./logs/xxl-job
